OUTPUT = ../../gen/analysis/output
INPUT = ../../gen/analysis/input
ANALYSIS = ../../src/analysis

all: $(OUTPUT)/anova1_airbnb.doc $(OUTPUT)/anova2_airbnb.doc $(OUTPUT)/anova3_airbnb.doc $(OUTPUT)/mod1_airbnb.doc $(OUTPUT)/mod2_airbnb.doc $(OUTPUT)/mod3_airbnb.doc $(OUTPUT)/mod5_airbnb.doc $(OUTPUT)/mod6_airbnb.doc $(OUTPUT)/eta_squared_anova1_airbnb.doc $(OUTPUT)/eta_squared_anova2_airbnb.doc $(OUTPUT)/eta_squared_anova3_airbnb.doc $(OUTPUT)/eta_squared_mod5_airbnb.doc $(OUTPUT)/eta_squared_mod6_airbnb.doc $(OUTPUT)/tukeytest_anova1_airbnb.doc $(OUTPUT)/tukeytest_anova2_airbnb.doc $(OUTPUT)/tukeytest_anova3_airbnb.doc $(OUTPUT)/tukeytest_mod5_airbnb.doc $(OUTPUT)/tukeytest_mod6_airbnb.doc $(OUTPUT)/levene_test1_airbnb.doc $(OUTPUT)/levene_test2_airbnb.doc $(OUTPUT)/levene_test3_airbnb.doc $(OUTPUT)/levene_test4_airbnb.doc $(OUTPUT)/levene_test5_airbnb.doc $(OUTPUT)/levene_test6_airbnb.doc $(OUTPUT)/shapiro_test1_airbnb.doc $(OUTPUT)/shapiro_test2_airbnb.doc $(OUTPUT)/shapiro_test3_airbnb.doc $(OUTPUT)/plot_review_score.png $(OUTPUT)/plot_listings.png

## sub-rules

### ANOVA

$(OUTPUT)/anova1_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/anova2_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/anova3_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/mod1_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/mod2_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/mod3_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/mod5_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/mod6_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

### Eta squared

$(OUTPUT)/eta_squared_anova1_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/eta_squared_anova2_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/eta_squared_anova3_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/eta_squared_mod5_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/eta_squared_mod6_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R


### Post hoc test

$(OUTPUT)/tukeytest_anova1_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/tukeytest_anova2_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/tukeytest_anova3_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/tukeytest_mod5_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/tukeytest_mod6_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

### Anova assumptions

$(OUTPUT)/levene_test1_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/levene_test2_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/levene_test3_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/levene_test4_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/levene_test5_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/levene_test6_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/shapiro_test1_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/shapiro_test2_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/shapiro_test3_airbnb.doc: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

### Plots 

$(OUTPUT)/plot_review_score.png: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R

$(OUTPUT)/plot_listings.png: $(ANALYSIS)/analysis_data_airbnb.R $(INPUT)/data_airbnb_uk_cleaned.csv
	R --vanilla < $(ANALYSIS)/analysis_data_airbnb.R
